// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz-ZT7SBckg09n_gI-srdPMhlYPA4OrKU',
    appId: '1:309111256017:web:8c94023cfdaa2cc0e5e6f0',
    messagingSenderId: '309111256017',
    projectId: 'paranagamatp',
    authDomain: 'paranagamatp.firebaseapp.com',
    storageBucket: 'paranagamatp.firebasestorage.app',
    measurementId: 'G-VN0DM00VRT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZBoEcfG-FIeLrwmrZqBhSh8vem7c-PrI',
    appId: '1:309111256017:android:2551594de5d14cd3e5e6f0',
    messagingSenderId: '309111256017',
    projectId: 'paranagamatp',
    storageBucket: 'paranagamatp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBM-muyo3FjwW7BVl689m6hJLgbTCW6V4',
    appId: '1:309111256017:ios:4e617fac65a33cebe5e6f0',
    messagingSenderId: '309111256017',
    projectId: 'paranagamatp',
    storageBucket: 'paranagamatp.firebasestorage.app',
    iosBundleId: 'com.example.paranagama',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBM-muyo3FjwW7BVl689m6hJLgbTCW6V4',
    appId: '1:309111256017:ios:4e617fac65a33cebe5e6f0',
    messagingSenderId: '309111256017',
    projectId: 'paranagamatp',
    storageBucket: 'paranagamatp.firebasestorage.app',
    iosBundleId: 'com.example.paranagama',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDz-ZT7SBckg09n_gI-srdPMhlYPA4OrKU',
    appId: '1:309111256017:web:bdfbd27ccd048c35e5e6f0',
    messagingSenderId: '309111256017',
    projectId: 'paranagamatp',
    authDomain: 'paranagamatp.firebaseapp.com',
    storageBucket: 'paranagamatp.firebasestorage.app',
    measurementId: 'G-H9QL04Z61N',
  );
}
